# Generated by Django 5.1.3 on 2024-11-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='date_registration',
            field=models.CharField(default='06.11.2024 16:21', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='date',
            field=models.CharField(default='06.11.2024 16:21', max_length=100, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='productphotomodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.productmodel'),
        ),
        migrations.AlterField(
            model_name='producttagsmodell',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='store.productmodel'),
        ),
    ]
