services:
  django:
    build:
      context: .
      dockerfile: dockerfile.django
    container_name: django_container
    ports:
      - "25565:25565"
  bot:
    build:
      context: .
      dockerfile: dockerfile.bot
    container_name: bot_container
    ports:
      - "8000:8000"
