version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: dockerfile.django
    container_name: django_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Монтируем SQLite файл
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  bot:
    build:
      context: .
      dockerfile: dockerfile.bot
    container_name: bot_container
    ports:
      - "25565:25565"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Монтируем SQLite файл
    environment:
      - PYTHONUNBUFFERED=1
