# Используем базовый образ Python
FROM python:3.10

# Установка рабочих директорий
WORKDIR /app

# Копируем файл зависимостей
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . .

# Установка переменных среды
ENV PYTHONUNBUFFERED=1

# Запуск бота
CMD ["python", "start_bot.py"]
